version: "3"

# networks:
#  vpcbr:
#   driver: bridge
#   ipam:
#    config:
#     - subnet: 172.28.0.0/16

services:

#  jenkins-master:
#   image: fapinheiro/jenkins-master:1.0.0
#   ports:
#    - 8080:8080
#    - 49187:49187
#   volumes:
#    - C:/Applics/Jenkins/JenkinsMaster:/opt/jenkins/JenkinsMaster

 openldap:
   image: fapinheiro/opendj-ldap:1.0.2
   ports:
    - 1389:1389
    - 1636:1636
    - 4444:4444
  #  networks:
  #   vpcbr:
  #    ipv4_address: 172.28.1.1
  #  extra_hosts:
    # - "localhost:192.168.99.100"